FROM golang:1.25 AS builder
WORKDIR /app

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o playback ./cmd/playback/main.go

FROM scratch
COPY --from=builder /app/playback /playback
CMD ["/playback"]

EXPOSE 8001